[package]
name = "world-id-faux-issuer"
version = "0.1.0"
edition.workspace = true
license.workspace = true
publish = false

[dependencies]
axum = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }
world-id-primitives = { workspace = true }
eddsa-babyjubjub = { workspace = true }
hex = { workspace = true }
secrecy = { workspace = true }
ruint = { workspace = true }
dotenvy = { workspace = true }
