[package]
name = "world-id-authenticator"
description = "World ID Credential crate"
publish = true
edition.workspace = true
version.workspace = true
license.workspace = true
authors.workspace = true
homepage.workspace = true
rust-version.workspace = true
repository.workspace = true
include = ["src/**/*", "tests/**/*", "Cargo.toml", "README.md"]

[features]
default = ["embed-zkeys"]
embed-zkeys = [
  "world-id-proof/embed-zkeys",
  "dep:rustls",
  "dep:webpki-roots",
  "dep:backon",
]

[dependencies]
alloy = { workspace = true }
ark-babyjubjub = { workspace = true }
ark-serialize = { workspace = true }
groth16-material = { workspace = true }
reqwest = { workspace = true }
poseidon2 = { workspace = true }
eddsa-babyjubjub = { workspace = true }
eyre = { workspace = true }
world-id-primitives = { workspace = true }
secrecy = { workspace = true }
taceo-oprf = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["rt-multi-thread", "macros", "net"] }
rand = { workspace = true }
backon = { workspace = true, optional = true }

# Optional
rustls = { workspace = true, optional = true }
webpki-roots = { workspace = true, optional = true }

# Internal
world-id-registry = { workspace = true }
world-id-signer = { workspace = true }
world-id-types = { workspace = true }
world-id-credential = { workspace = true }
world-id-request = { workspace = true }
world-id-proof = { workspace = true }

[dev-dependencies]
backon = { workspace = true }
ruint = { workspace = true }
rand = { workspace = true }
serde_json = { workspace = true }
mockito = { workspace = true }
