[package]
name = "test-utils"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
alloy = { workspace = true, default-features = false, features = ["contract", "reqwest", "rpc", "signer-local", "sol-types", "json"] }
alloy-node-bindings = "1.0.38"
eyre = { workspace = true }
hex = { workspace = true }
serde_json = { workspace = true }
