[package]
name = "test-utils"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
alloy = { workspace = true, default-features = false, features = ["rpc", "sol-types"] }
alloy-node-bindings = "1.0.38"
eyre = "0.6"
hex = { workspace = true }
serde_json = { workspace = true }
