[package]
name = "world-id-primitives"
description = "Contains the raw base primitives (without implementations) for the World ID Protocol."
version.workspace = true
license.workspace = true
edition.workspace = true


[dependencies]
alloy-primitives = { version = "1", default-features = false, features = ["serde", "std"] }
ark-babyjubjub = { workspace = true }
ark-bn254 = { workspace = true }
ark-ff = { workspace = true }
ark-groth16 = { workspace = true }
ark-serde-compat = { workspace = true }
ark-serialize = { workspace = true }
arrayvec = { version = "0.7", features = ["serde"] }
circom-types = { workspace = true, features = ["groth16"] }
groth16-material = { workspace = true, features = ["circom"] }
eddsa-babyjubjub = { workspace = true }
hex = { workspace = true }
oprf-core = { workspace = true }
ruint = { workspace = true, features = ["ark-ff-05"] }
serde_json = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
k256 = { workspace = true, features = ["ecdsa"] }

[dev-dependencies]
ciborium = "0.2.2"
