[package]
name = "world-id-gateway"
version = "0.1.0"
edition.workspace = true
license.workspace = true
publish = false

[lib]
path = "src/lib.rs"

[dependencies]
world-id-services-common = { workspace = true }

alloy = { workspace = true, features = [
  "json-rpc",
  "node-bindings",
  "rpc-client",
  "rpc-types-debug",
  "rpc-types-trace",
  "signer-aws",
] }

aws-config = { workspace = true }
aws-sdk-kms = { workspace = true }
axum = { workspace = true, features = ["macros", "json"] }
clap = { workspace = true, features = ["derive", "env"] }
world-id-core = { workspace = true, features = [
  "authenticator",
  "embed-zkeys",
] }
world-id-primitives = { workspace = true, features = ["openapi"] }
dotenvy = { workspace = true }
hex = { workspace = true }
moka = { workspace = true }
once_cell = { workspace = true }
redis = { workspace = true, features = ["tokio-comp", "connection-manager"] }
serde = { workspace = true }
serde_json = { workspace = true }
strum = { workspace = true, features = ["derive"] }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["rt-multi-thread", "macros", "time"] }
tower-http = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["json"] }
telemetry-batteries = { workspace = true }
metrics = { workspace = true }
utoipa = { workspace = true }
uuid = { workspace = true, features = ["v4"] }

[dev-dependencies]
world-id-test-utils = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

[features]
integration-tests = [] # running integration tests requires running external services (i.e. Postgres)
