[package]
name = "world-id-oprf-dev-client"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
alloy = { workspace = true, features = ["full", "rpc", "rpc-client-ws"] }
ark-babyjubjub = { workspace = true }
ark-ff = { workspace = true }
backon = { workspace = true }
clap = { workspace = true, features = ["derive", "env"] }
eyre = { workspace = true }
humantime = { workspace = true }
rand = { workspace = true }
rand_chacha = { workspace = true }
rustls = { workspace = true }
secrecy = { workspace = true }
taceo-nodes-observability = { workspace = true }
taceo-oprf = { workspace = true, features = ["dev-client", "core"] }
taceo-oprf-test-utils = { workspace = true }
world-id-test-utils = { workspace = true }
tokio = { workspace = true, features = [
  "net",
  "rt-multi-thread",
  "signal",
  "sync",
  "time",
  "tokio-macros",
] }
tracing = { workspace = true }
uuid = { workspace = true, features = ["serde", "v4"] }
webpki-roots = { workspace = true }
world-id-core = { workspace = true, features = ["authenticator", "embed-zkeys"] }
world-id-primitives = { workspace = true }
