[profile.default]
src = "src"
out = "out"
libs = ["lib"]
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
# Enable optimizer
optimizer = true
# How aggressively to optimize (higher = more runtime-opt, bigger bytecode)
optimizer_runs = 10000
via_ir = true
ffi = true
memory_limit = 1073741824
gas_limit = "18446744073709551615"

fs_permissions = [
    { access = "read", path = "script/config/" },
    { access = "read-write", path = "deployments/" },
]

[lint]
exclude_lints = ["screaming-snake-case-const"]

[fmt]
ignore = ["lib"]
