[package]
name = "world-id-oprf-node"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
alloy = { workspace = true, features = ["full", "rpc", "rpc-client-ws"] }
ark-babyjubjub = { workspace = true }
ark-bn254 = { workspace = true }
ark-ff = { workspace = true }
ark-groth16 = { workspace = true }
async-trait = { workspace = true }
aws-config = { workspace = true, features = ["behavior-version-latest"] }
axum = { workspace = true, features = ["json", "macros"] }
circom-types = { workspace = true, features = ["bn254", "groth16", "zkey"] }
clap = { workspace = true, features = ["derive", "env"] }
eyre = { workspace = true }
futures = { workspace = true }
humantime = { workspace = true }
rustls = { workspace = true }
secrecy = { workspace = true }
serde_json = { workspace = true }
taceo-nodes-common = { workspace = true }
taceo-nodes-observability = { workspace = true }
taceo-oprf = { workspace = true, features = ["service"] }
thiserror = { workspace = true }
tokio = { workspace = true, features = [
  "net",
  "rt-multi-thread",
  "signal",
  "sync",
  "time",
  "tokio-macros",
] }
tokio-util = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true, features = ["serde", "v4"] }
world-id-core = { workspace = true, features = ["authenticator", "embed-zkeys"] }
world-id-primitives = { workspace = true }
moka = { workspace = true }
metrics = { workspace = true }

[dev-dependencies]
test-utils = { workspace = true }
