[package]
name = "common"
edition.workspace = true
version.workspace = true
license.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
tower-http = { workspace = true }

alloy = { workspace = true, features = [
    "json-rpc",
    "network",
    "node-bindings",
    "providers",
    "provider-ws",
    "rpc-client",
    "rpc-types-debug",
    "rpc-types-trace",
    "signer-aws",
    "signer-local",
    "transport-http",
] }
serde.workspace = true
thiserror.workspace = true
url.workspace = true
tracing.workspace = true

config = "0.15.19"
aws-sdk-kms = "1.0.0"
aws-config = "1.0.0"
clap = { version = "4.5.54", features = ["derive", "env"] }
tower = "0.5.3"
governor = "0.10.4"

[dev-dependencies]
tempfile = "3"