[package]
name = "world-id-services-common"
version = "0.1.0"
edition.workspace = true
license.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
axum = { workspace = true }
tower-http = { workspace = true }
http = { workspace = true }
alloy = { workspace = true, features = [
    "json-rpc",
    "network",
    "node-bindings",
    "providers",
    "provider-ws",
    "reqwest",
    "rpc-client",
    "rpc-types-debug",
    "rpc-types-trace",
    "signer-aws",
    "signer-local",
    "transport-http",
] }
serde = { workspace = true }
thiserror = { workspace = true }
url = { workspace = true }
tracing = { workspace = true }

backon = { workspace = true }
config = { workspace = true }
aws-sdk-kms = { workspace = true }
aws-config = { workspace = true }
clap = { workspace = true, features = ["derive", "env"] }
tower = { workspace = true }
governor = { workspace = true }
tokio = { workspace = true, features = ["time"] }

[dev-dependencies]
axum = { workspace = true }
tempfile = { workspace = true }
tokio = { workspace = true, features = ["full"] }
