[package]
name = "common"
edition.workspace = true
version.workspace = true
license.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
alloy = { workspace = true, features = [
    "json-rpc",
    "node-bindings",
    "rpc-client",
    "rpc-types-debug",
    "rpc-types-trace",
    "signer-aws",
] }
serde.workspace = true
url.workspace = true
anyhow.workspace = true
tracing.workspace = true

config = "0.15.19"
aws-sdk-kms = "1.0.0"
aws-config = "1.0.0"
clap = "4.5.54"
tower = "0.5.3"
governor = "0.10.4"