name: Build and Push (world-id-oprf-node)

on:
  workflow_dispatch:
  push:
    tags:
      - 'world-id-oprf-node-v*'

permissions:
  contents: read

jobs:
  workflow:
    uses: ./.github/workflows/build-and-push.yml
    with:
      image-name: world-id-oprf-node
      dockerfile: services/oprf-node/Dockerfile.oprf-node

